-- ============================================================
-- Script MySQL - Sistema de Inventario de Vehículos
-- PDM115 - Grupo 02
-- Migrado desde SQLite (DatabaseContract.java)
-- ============================================================

CREATE DATABASE IF NOT EXISTS inventario_gpo02
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_spanish_ci;

USE inventario_gpo02;

-- ============================================================
-- Catálogos raíz (sin dependencias)
-- ============================================================

CREATE TABLE IF NOT EXISTS OPCIONCRUD (
    ID_OPCION       VARCHAR(50)     NOT NULL,
    DES_OPCION      VARCHAR(255)    NOT NULL,
    NUM_CRUD        INT             NOT NULL,
    PRIMARY KEY (ID_OPCION)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS USUARIO (
    ID_USUARIO      VARCHAR(50)     NOT NULL,
    NOM_USUARIO     VARCHAR(100)    NOT NULL,
    CLAVE           VARCHAR(255)    NOT NULL,
    PRIMARY KEY (ID_USUARIO)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PAIS (
    ID_PAIS         INT             NOT NULL AUTO_INCREMENT,
    NOMBRE_PAIS     VARCHAR(100)    NOT NULL,
    PRIMARY KEY (ID_PAIS)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS MARCA (
    ID_MARCA        INT             NOT NULL AUTO_INCREMENT,
    NOMBRE_MARCA    VARCHAR(100)    NOT NULL,
    PRIMARY KEY (ID_MARCA)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS TIPO_VEHICULO (
    ID_TIPO_VEHICULO            INT             NOT NULL AUTO_INCREMENT,
    DESCRIPCION_TIPO_VEHICULO   VARCHAR(100)    NOT NULL,
    PRIMARY KEY (ID_TIPO_VEHICULO)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS TIPO_TRANSPORTE (
    ID_TIPO_TRANSPORTE              INT             NOT NULL AUTO_INCREMENT,
    DESCRIPCION_TIPO_TRANSPORTE     VARCHAR(100)    NOT NULL,
    CAPACIDAD_MAX_VEHICULOS         INT             NOT NULL,
    PRIMARY KEY (ID_TIPO_TRANSPORTE)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS TIPO_DESPERFECTO (
    ID_TIPO_DESPERFECTO             INT             NOT NULL AUTO_INCREMENT,
    NOMBRE_TIPO_DESPERFECTO         VARCHAR(100)    NOT NULL,
    DESCRIPCION_TIPO_DESPERFECTO    TEXT,
    PRIMARY KEY (ID_TIPO_DESPERFECTO)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS TALLER (
    ID_TALLER           INT             NOT NULL AUTO_INCREMENT,
    NOMBRE_TALLER       VARCHAR(100)    NOT NULL,
    DIRECCION_TALLER    VARCHAR(255)    NOT NULL,
    TELEFONO_TALLER     VARCHAR(20)     NOT NULL,
    AUTORIZADO          TINYINT(1)      NOT NULL,
    PRIMARY KEY (ID_TALLER)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PERSONAL_INTERNO (
    ID_PERSONAL         INT             NOT NULL AUTO_INCREMENT,
    NOMBRE_PERSONAL     VARCHAR(100)    NOT NULL,
    APELLIDO_PERSONAL   VARCHAR(100)    NOT NULL,
    CARGO               VARCHAR(100)    NOT NULL,
    PRIMARY KEY (ID_PERSONAL)
) ENGINE=InnoDB;

-- ============================================================
-- Jerarquía geográfica
-- ============================================================

CREATE TABLE IF NOT EXISTS DEPARTAMENTO (
    ID_DEPARTAMENTO     INT             NOT NULL AUTO_INCREMENT,
    ID_PAIS             INT             NOT NULL,
    NOMBRE_DEPARTAMENTO VARCHAR(100)    NOT NULL,
    PRIMARY KEY (ID_DEPARTAMENTO),
    FOREIGN KEY (ID_PAIS) REFERENCES PAIS(ID_PAIS)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS MUNICIPIO (
    ID_MUNICIPIO        INT             NOT NULL AUTO_INCREMENT,
    ID_DEPARTAMENTO     INT,
    NOMBRE_MUNICIPIO    VARCHAR(100)    NOT NULL,
    PRIMARY KEY (ID_MUNICIPIO),
    FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS DISTRITO (
    ID_DISTRITO         INT             NOT NULL AUTO_INCREMENT,
    ID_MUNICIPIO        INT,
    NOMBRE_DISTRITO     VARCHAR(100)    NOT NULL,
    PRIMARY KEY (ID_DISTRITO),
    FOREIGN KEY (ID_MUNICIPIO) REFERENCES MUNICIPIO(ID_MUNICIPIO)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

-- ============================================================
-- Tablas que dependen de geografía / acceso
-- ============================================================

CREATE TABLE IF NOT EXISTS ACCESOUSUARIO (
    ID_OPCION       VARCHAR(50)     NOT NULL,
    ID_USUARIO      VARCHAR(50)     NOT NULL,
    PRIMARY KEY (ID_OPCION, ID_USUARIO),
    FOREIGN KEY (ID_OPCION)  REFERENCES OPCIONCRUD(ID_OPCION)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS BODEGA (
    ID_BODEGA           INT             NOT NULL AUTO_INCREMENT,
    ID_DISTRITO         INT,
    NOMBRE_BODEGA       VARCHAR(100)    NOT NULL,
    DIRECCION_BODEGA    VARCHAR(255)    NOT NULL,
    PRIMARY KEY (ID_BODEGA),
    FOREIGN KEY (ID_DISTRITO) REFERENCES DISTRITO(ID_DISTRITO)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS IMPORTADOR (
    ID_IMPORTADOR           INT             NOT NULL AUTO_INCREMENT,
    ID_DISTRITO             INT,
    NOMBRE_IMPORTADOR       VARCHAR(100)    NOT NULL,
    APELLIDO_IMPORTADOR     VARCHAR(100)    NOT NULL,
    APELLIDO_CASADA         VARCHAR(100),
    GENERO                  VARCHAR(10)     NOT NULL,
    DIRECCION_IMPORTADOR    VARCHAR(255)    NOT NULL,
    FECHA_NACIMIENTO        VARCHAR(20)     NOT NULL,
    CORREO_ELECTRONICO      VARCHAR(150),
    NUI                     VARCHAR(20)     NOT NULL,
    NOMBRE_RESPONSABLE      VARCHAR(100),
    PRIMARY KEY (ID_IMPORTADOR),
    FOREIGN KEY (ID_DISTRITO) REFERENCES DISTRITO(ID_DISTRITO)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

-- ============================================================
-- Tablas que dependen de catálogos
-- ============================================================

CREATE TABLE IF NOT EXISTS MODELO (
    ID_MODELO       INT             NOT NULL AUTO_INCREMENT,
    ID_MARCA        INT,
    NOMBRE_MODELO   VARCHAR(100)    NOT NULL,
    PRIMARY KEY (ID_MODELO),
    FOREIGN KEY (ID_MARCA) REFERENCES MARCA(ID_MARCA)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS SECCION (
    ID_SECCION          INT             NOT NULL AUTO_INCREMENT,
    ID_BODEGA           INT,
    NIVEL               INT             NOT NULL,
    CAPACIDAD_MAXIMA    INT             NOT NULL,
    CAPACIDAD_ACTUAL    INT             NOT NULL,
    PRIMARY KEY (ID_SECCION),
    FOREIGN KEY (ID_BODEGA) REFERENCES BODEGA(ID_BODEGA)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS TRANSPORTE (
    ID_TRANSPORTE               INT             NOT NULL AUTO_INCREMENT,
    ID_TIPO_TRANSPORTE          INT,
    PLACA                       VARCHAR(15)     NOT NULL,
    DESCRIPCION_TRANSPORTE      VARCHAR(255),
    PRIMARY KEY (ID_TRANSPORTE),
    FOREIGN KEY (ID_TIPO_TRANSPORTE) REFERENCES TIPO_TRANSPORTE(ID_TIPO_TRANSPORTE)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

-- ============================================================
-- Tablas transaccionales
-- ============================================================

CREATE TABLE IF NOT EXISTS TELEFONO_IMPORTADOR (
    ID_TELEFONO         INT             NOT NULL AUTO_INCREMENT,
    ID_IMPORTADOR       INT,
    NUMERO              VARCHAR(20)     NOT NULL,
    TIPO                VARCHAR(20)     NOT NULL,
    PRIMARY KEY (ID_TELEFONO),
    FOREIGN KEY (ID_IMPORTADOR) REFERENCES IMPORTADOR(ID_IMPORTADOR)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS IMPORTACION (
    ID_IMPORTACION      INT             NOT NULL AUTO_INCREMENT,
    ID_IMPORTADOR       INT,
    FECHA_IMPORTACION   VARCHAR(20)     NOT NULL,
    PRIMARY KEY (ID_IMPORTACION),
    FOREIGN KEY (ID_IMPORTADOR) REFERENCES IMPORTADOR(ID_IMPORTADOR)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS VEHICULO (
    ID_VEHICULO         INT             NOT NULL AUTO_INCREMENT,
    ID_TIPO_VEHICULO    INT,
    ID_SECCION          INT,
    ID_MODELO           INT,
    ID_IMPORTACION      INT,
    VIN                 VARCHAR(17)     NOT NULL,
    ANIO                INT             NOT NULL,
    COLOR_VEHICULO      VARCHAR(50)     NOT NULL,
    ESTADO_VEHICULO     VARCHAR(50)     NOT NULL,
    PRIMARY KEY (ID_VEHICULO),
    FOREIGN KEY (ID_TIPO_VEHICULO) REFERENCES TIPO_VEHICULO(ID_TIPO_VEHICULO)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (ID_SECCION)       REFERENCES SECCION(ID_SECCION)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (ID_MODELO)        REFERENCES MODELO(ID_MODELO)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (ID_IMPORTACION)   REFERENCES IMPORTACION(ID_IMPORTACION)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS DETALLE_DESPERFECTO (
    ID_DETALLE_DESPERFECTO  INT             NOT NULL AUTO_INCREMENT,
    ID_VEHICULO             INT,
    ID_TIPO_DESPERFECTO     INT,
    DESCRIPCION_DETALLE     TEXT            NOT NULL,
    FECHA_REGISTRO          VARCHAR(20)     NOT NULL,
    PRIMARY KEY (ID_DETALLE_DESPERFECTO),
    FOREIGN KEY (ID_VEHICULO)         REFERENCES VEHICULO(ID_VEHICULO)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (ID_TIPO_DESPERFECTO) REFERENCES TIPO_DESPERFECTO(ID_TIPO_DESPERFECTO)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS FOTO_DESPERFECTO (
    ID_FOTO_DESPERFECTO         INT             NOT NULL AUTO_INCREMENT,
    ID_DETALLE_DESPERFECTO      INT,
    RUTA_IMAGEN                 VARCHAR(255)    NOT NULL,
    FECHA_TOMA                  VARCHAR(20)     NOT NULL,
    PRIMARY KEY (ID_FOTO_DESPERFECTO),
    FOREIGN KEY (ID_DETALLE_DESPERFECTO) REFERENCES DETALLE_DESPERFECTO(ID_DETALLE_DESPERFECTO)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS MOVIMIENTO (
    ID_MOVIMIENTO       INT             NOT NULL AUTO_INCREMENT,
    ID_TRANSPORTE       INT,
    ID_PERSONAL         INT,
    ID_VEHICULO         INT,
    ID_BODEGA           INT,
    TIPO_MOVIMIENTO     VARCHAR(50)     NOT NULL,
    FECHA_MOVIMIENTO    VARCHAR(20)     NOT NULL,
    MOTIVO              TEXT            NOT NULL,
    PRIMARY KEY (ID_MOVIMIENTO),
    FOREIGN KEY (ID_TRANSPORTE) REFERENCES TRANSPORTE(ID_TRANSPORTE)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (ID_VEHICULO)   REFERENCES VEHICULO(ID_VEHICULO)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (ID_PERSONAL)   REFERENCES PERSONAL_INTERNO(ID_PERSONAL)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (ID_BODEGA)     REFERENCES BODEGA(ID_BODEGA)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS REPARACION (
    ID_REPARACION               INT             NOT NULL AUTO_INCREMENT,
    ID_TALLER                   INT,
    ID_VEHICULO                 INT,
    FECHA_INICIO                VARCHAR(20)     NOT NULL,
    FECHA_FIN                   VARCHAR(20),
    DESCRIPCION_TRABAJO         TEXT,
    APTO_PARA_VENTA             TINYINT(1),
    REQUIERE_OTRA_REPARACION    TINYINT(1),
    PRIMARY KEY (ID_REPARACION),
    FOREIGN KEY (ID_TALLER)   REFERENCES TALLER(ID_TALLER)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (ID_VEHICULO) REFERENCES VEHICULO(ID_VEHICULO)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS VENTA (
    ID_VENTA        INT             NOT NULL AUTO_INCREMENT,
    ID_IMPORTADOR   INT,
    ID_VEHICULO     INT,
    FECHA_VENTA     VARCHAR(20)     NOT NULL,
    PRECIO          DECIMAL(10,2)   NOT NULL,
    PRIMARY KEY (ID_VENTA),
    FOREIGN KEY (ID_VEHICULO)   REFERENCES VEHICULO(ID_VEHICULO)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (ID_IMPORTADOR) REFERENCES IMPORTADOR(ID_IMPORTADOR)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;
